Added Kinesis-streams module
sourcefuse/terraform-aws-arc-kinesis-stream pull request #1
Opened 2024-07-14 18:29 UTC by mayank0202

<img width="1284" alt="Screenshot 2024-07-15 at 7 33 26 PM" src="https://github.com/user-attachments/assets/88257f67-4c9a-4db3-b2f5-1933c3f7597e">

2024-07-22 10:32 UTC, vijay-stephen requested changes, later dismissed

2024-07-22 10:32 UTC, vijay-stephen commented on main.tf
> +  count = var.consumer_count // This allows you to dynamically control the number of Kinesis stream consumers
Please use `for_each` instead of `count`

2024-07-22 10:32 UTC, vijay-stephen commented on main.tf
> +  name       = format("%s-consumer-%s", local.stream_name, count.index)
Please don't use format, its outdated.

2024-07-22 10:34 UTC, vijay-stephen commented
@tsaucier-sf Since this is a small module shall we use the same module for firehose as well ?
We need to rename the module to `terraform-aws-arc-kinesis-stream`

2024-07-23 16:20 UTC, mayank0202 commented
> @tsaucier-sf Since this is a small module shall we use the same module for firehose as well ? We need to rename the module to `terraform-aws-arc-kinesis-stream`

I think firehose one should be different so that the code doesn't go so long

2024-07-23 16:24 UTC, tsaucier-sf approved these changes

2024-07-23 16:38 UTC, tsaucier-sf commented
> > @tsaucier-sf Since this is a small module shall we use the same module for firehose as well ? We need to rename the module to `terraform-aws-arc-kinesis-stream`
> 
> I think firehose one should be different so that the code doesn't go so long

Agreed.

2024-07-23 16:54 UTC, merged